package com.rulesmaker.repository;

// Generated 11-Jul-2015 15:30:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fltask generated by hbm2java
 */
@Entity
@Table(name = "fltask", catalog = "rulesmaker")
public class Fltask implements java.io.Serializable {

	private Integer idFltask;
	private String name;
	private String idtask;
	private String tip;

	public Fltask() {
	}

	public Fltask(String name, String idtask) {
		this.name = name;
		this.idtask = idtask;
	}

	public Fltask(String name, String idtask, String tip) {
		this.name = name;
		this.idtask = idtask;
		this.tip = tip;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_fltask", unique = true, nullable = false)
	public Integer getIdFltask() {
		return this.idFltask;
	}

	public void setIdFltask(Integer idFltask) {
		this.idFltask = idFltask;
	}

	@Column(name = "name", nullable = false, length = 500)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "idtask", nullable = false, length = 20)
	public String getIdtask() {
		return this.idtask;
	}

	public void setIdtask(String idtask) {
		this.idtask = idtask;
	}

	@Column(name = "tip", length = 10000)
	public String getTip() {
		return this.tip;
	}

	public void setTip(String tip) {
		this.tip = tip;
	}

}
